name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker and Docker Compose
        uses: docker-practice/actions-setup-docker@v1.1.1
        with:
          docker_version: 20.10
          docker_compose: true

      - name: Deploy
        run: |
          cd ${{ secrets.DEPLOY_PATH }}
          git pull
          docker-compose build
          docker-compose up -d